# Generated by Django 6.0 on 2025-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventdefinition",
            old_name="rules",
            new_name="params",
        ),
        migrations.AddField(
            model_name="eventdefinition",
            name="cooldown_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional wait time after an event ends before it can start again.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventdefinition",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Length of the event in seconds, used to compute decay.",
            ),
        ),
        migrations.AddField(
            model_name="eventdefinition",
            name="probability_weight",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Higher weight increases the chances this definition is selected.",
            ),
        ),
        migrations.AddField(
            model_name="eventdefinition",
            name="type",
            field=models.CharField(
                choices=[("BOOM", "boom"), ("CRASH", "crash"), ("FOCUS", "focus")],
                default="BOOM",
                max_length=16,
            ),
        ),
    ]
