# Generated by Django 6.0 on 2025-12-27 15:42

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_core_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdefinition",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                help_text="Duration in seconds the event should run before expiring.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="probability_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
