# Generated by Django 6.0 on 2025-12-26 09:42
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_eventdefinition_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdefinition",
            name="cooldown_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional wait time after an event ends before it can start again.",
                null=True,
            ),
        ),
    ]
