# Generated by Django 6.0 on 2025-12-29 16:19

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_eventdefinition_rules_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdefinition",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Arbitrary configuration such as start_multiplier or target_drink_ids.",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="probability_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Higher weight increases the chances this definition is selected.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
