# Generated by Django 6.1.1 on 2026-09-23 09:42

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0008_field_verbose_names"),
        ("events", "0005_alter_eventdefinition_params_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeevent",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_events",
                to="bars.bar",
                verbose_name="bar",
            ),
        ),
        migrations.AlterField(
            model_name="activeevent",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_events",
                to="events.eventdefinition",
                verbose_name="event definition",
            ),
        ),
        migrations.AlterField(
            model_name="activeevent",
            name="ends_at",
            field=models.DateTimeField(verbose_name="ends at"),
        ),
        migrations.AlterField(
            model_name="activeevent",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="activeevent",
            name="starts_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="starts at"),
        ),
        migrations.AlterField(
            model_name="activeevent",
            name="state",
            field=models.JSONField(blank=True, default=dict, verbose_name="state"),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_definitions",
                to="bars.bar",
                verbose_name="bar",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="cooldown_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional wait time after an event ends before it can start again.",
                null=True,
                verbose_name="cooldown (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                help_text="Duration in seconds the event should run before expiring.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="duration (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Arbitrary configuration such as start_multiplier or target_drink_ids.",
                verbose_name="parameters",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="probability_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Higher weight increases the chances this definition is selected.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="probability weight",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="type",
            field=models.CharField(
                choices=[
                    ("boom", "boom"),
                    ("crash", "crash"),
                    ("focus", "focus"),
                    ("normalize", "normalize"),
                ],
                max_length=16,
                verbose_name="type",
            ),
        ),
    ]
