from channels.db import database_sync_to_async
from channels.generic.websocket import AsyncJsonWebsocketConsumer
from django.conf import settings
from django.utils import timezone

from bars.models import Bar
from market.serializers import (
    build_event_payload,
    build_market_status_payload,
    build_price_update_payload,
)


class MarketConsumer(AsyncJsonWebsocketConsumer):
    """Bridges websocket clients to the market.<bar_id> channel layer groups."""

    async def connect(self):
        """Accept the websocket if the related Bar exists and send an initial snapshot."""
        self.bar_id = self.scope["url_route"]["kwargs"]["bar_id"]
        self.group_name = settings.MARKET_CHANNEL_GROUP.format(bar_id=self.bar_id)
        self.bar = await self._load_bar()
        if not self.bar:
            await self.close()
            return

        # Join the market group and acknowledge the websocket open before sending any data.
        await self.channel_layer.group_add(self.group_name, self.channel_name)
        await self.accept()
        snapshot_payload, events = await self._build_snapshot()
        await self.send_json(snapshot_payload)
        await self._send_event_notifications(events)

    async def disconnect(self, code):
        """Leave the market channel group when the websocket disconnects."""
        await self.channel_layer.group_discard(self.group_name, self.channel_name)

    async def market_message(self, event):
        """Proxy incoming layer messages directly to the websocket client."""
        await self.send_json(event["data"])

    async def receive_json(self, content, **kwargs):
        """Handle simple control messages generated by the client such as pings."""
        if content.get("type") == "ping":
            await self.send_json(
                {
                    "type": "pong",
                    "bar_id": self.bar_id,
                    "timestamp": timezone.now().isoformat(),
                }
            )

    @database_sync_to_async
    def _load_bar(self):
        """Load the requested Bar slug from the ORM so sync queries run safely."""
        return Bar.objects.filter(slug=self.bar_id).first()

    @database_sync_to_async
    def _fetch_drinks(self):
        """Retrieve every drink configured for the bar."""
        return list(self.bar.drinks.all())

    @database_sync_to_async
    def _fetch_active_events(self):
        """Grab the active events tied to the bar, including their definitions."""
        events = self.bar.active_events.filter(is_active=True)
        events = events.select_related("definition")
        events = events.order_by("starts_at")
        return list(events)

    async def _build_snapshot(self):
        """Assemble the initial payload combining prices and events for the current bar."""
        drinks = await self._fetch_drinks()
        events = await self._fetch_active_events()
        return build_price_update_payload(self.bar_id, drinks, events), events

    async def _send_event_notifications(self, events):
        """Notify the websocket about each active event plus a summarized market status."""
        for event in events:
            await self.send_json(build_event_payload(self.bar_id, event, "event.started"))
        status = "running" if events else "idle"
        await self.send_json(
            build_market_status_payload(
                self.bar_id,
                status,
                metadata={"active_event_count": len(events)},
            )
        )
