# Generated by Django 6.0 on 2025-12-27 15:42

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _set_initial_current_price(apps, schema_editor):
    Drink = apps.get_model("market", "Drink")
    Drink.objects.update(current_price=models.F("base_price"))


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0002_bar_last_tick_at_bar_price_point_retention_ticks_and_more"),
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Created at"),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Last modified at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "running"), ("paused", "paused"), ("closed", "closed")],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PricePoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Created at"),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Last modified at"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "price point",
                "verbose_name_plural": "price points",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="drink",
            options={"ordering": ["bar", "name"], "verbose_name": "drink", "verbose_name_plural": "drinks"},
        ),
        migrations.AlterModelOptions(
            name="trade",
            options={"ordering": ["-occurred_at"], "verbose_name": "trade", "verbose_name_plural": "trades"},
        ),
        migrations.RemoveField(
            model_name="trade",
            name="executed_at",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="quantity",
        ),
        migrations.AddField(
            model_name="drink",
            name="current_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="drink",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("9999.99"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="drink",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="drink",
            name="rounding_step",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="drink",
            name="volatility",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.05"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="drink",
            name="weight",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.00"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="occurred_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="trade",
            name="qty",
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="drink",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["bar", "occurred_at"], name="market_trade_bar_occurred_idx"),
        ),
        migrations.AddConstraint(
            model_name="drink",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_price__lte", models.F("max_price"))), name="market_drink_min_lte_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="drink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_price__lte", models.F("base_price")), ("base_price__lte", models.F("max_price"))
                ),
                name="market_drink_base_within",
            ),
        ),
        migrations.AddConstraint(
            model_name="drink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_price__gte", models.F("min_price")), ("current_price__lte", models.F("max_price"))
                ),
                name="market_drink_current_within_bounds",
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="market_sessions", to="bars.bar"
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="lastmodified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_lastmodified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last modified by",
            ),
        ),
        migrations.AddField(
            model_name="pricepoint",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="price_points", to="bars.bar"
            ),
        ),
        migrations.AddField(
            model_name="pricepoint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="pricepoint",
            name="drink",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="price_points", to="market.drink"
            ),
        ),
        migrations.AddField(
            model_name="pricepoint",
            name="lastmodified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_lastmodified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last modified by",
            ),
        ),
        migrations.AddIndex(
            model_name="marketsession",
            index=models.Index(fields=["bar", "started_at"], name="market_session_bar_started_idx"),
        ),
        migrations.AddIndex(
            model_name="pricepoint",
            index=models.Index(fields=["bar", "recorded_at"], name="market_pricepoint_bar_at_idx"),
        ),
        migrations.AddIndex(
            model_name="pricepoint",
            index=models.Index(fields=["drink", "recorded_at"], name="market_pricepoint_drink_at_idx"),
        ),
        migrations.RunPython(_set_initial_current_price, migrations.RunPython.noop),
    ]
