# Generated by Django 6.0 on 2025-12-27 16:15

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_marketsession_pricepoint_alter_drink_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.01"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
