# Generated by Django 6.1.1 on 2026-09-23 09:42

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0008_field_verbose_names"),
        ("market", "0003_alter_drink_min_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketsession",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "market session",
                "verbose_name_plural": "market sessions",
            },
        ),
        migrations.AlterField(
            model_name="drink",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drinks",
                to="bars.bar",
                verbose_name="bar",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="base price",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="current_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="current price",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("9999.99"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="maximum price",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.01"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="minimum price",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="drink",
            name="rounding_step",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="rounding step",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="volatility",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.05"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="volatility",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="weight",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.00"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="weight",
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_sessions",
                to="bars.bar",
                verbose_name="bar",
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ended at"),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="metadata"),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="started at"),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "running"),
                    ("paused", "paused"),
                    ("closed", "closed"),
                ],
                default="running",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="pricepoint",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_points",
                to="bars.bar",
                verbose_name="bar",
            ),
        ),
        migrations.AlterField(
            model_name="pricepoint",
            name="drink",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_points",
                to="market.drink",
                verbose_name="drink",
            ),
        ),
        migrations.AlterField(
            model_name="pricepoint",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="pricepoint",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="recorded at"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="bars.bar",
                verbose_name="bar",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="drink",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="market.drink",
                verbose_name="drink",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="occurred_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="occurred at"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="qty",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantity",
            ),
        ),
    ]
