# Generated by Django 6.0 on 2025-12-27 15:42

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="last_tick_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bar",
            name="price_point_retention_ticks",
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="bar",
            name="reversion_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.100"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="tick_counter",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bar",
            name="tick_interval_seconds",
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
