# Generated by Django 6.1.1 on 2026-09-23 08:40

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0005_barassignment_commoninfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="impulse_factor",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="normalization_factor",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.500"),
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
    ]
