# Generated by Django 6.1.1 on 2026-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0006_bar_trade_factors"),
    ]

    operations = [
        migrations.AddField(
            model_name="barassignment",
            name="role",
            field=models.CharField(
                choices=[("operator", "operator"), ("manager", "manager")],
                default="operator",
                max_length=16,
            ),
        ),
    ]
