# Generated by Django 6.1.1 on 2026-09-23 09:42

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0007_barassignment_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bar",
            options={
                "ordering": ["name"],
                "verbose_name": "bar",
                "verbose_name_plural": "bars",
            },
        ),
        migrations.AlterField(
            model_name="bar",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="bar",
            name="impulse_factor",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="impulse factor",
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="last_tick_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last tick at"),
        ),
        migrations.AlterField(
            model_name="bar",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="bar",
            name="normalization_factor",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.500"),
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="normalization factor",
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="price_point_retention_ticks",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="price point retention (ticks)",
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="reversion_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.100"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="reversion rate",
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="slug",
            field=models.SlugField(max_length=64, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="bar",
            name="tick_counter",
            field=models.PositiveBigIntegerField(default=0, verbose_name="tick counter"),
        ),
        migrations.AlterField(
            model_name="bar",
            name="tick_interval_seconds",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="tick interval (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="barassignment",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                related_query_name="assignment",
                to="bars.bar",
                verbose_name="bar",
            ),
        ),
        migrations.AlterField(
            model_name="barassignment",
            name="role",
            field=models.CharField(
                choices=[("operator", "operator"), ("manager", "manager")],
                default="operator",
                max_length=16,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="barassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bar_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
